# Config file for compose, a tool that allows for easily managing multiple docker containers.
# https://docs.docker.com/compose/

include:
    - ./Services/Economy/docker-compose.yaml
    - ./Services/TextFilter/docker-compose.yaml

services:
    surreal-db:
        image: surrealdb/surrealdb:v1.5.4
        container_name: surreal-db
        #user: ":" uncomment if having issues when running locally
        ports:
            - 8000:8000
        restart: unless-stopped
        volumes:
            - surrealdb-data:/database
        command:
            - start
            - --log=trace
            - --user=root
            - --pass=root
            - --allow-scripting
            - file:database

volumes:
  surrealdb-data: