name: Feature request
description: Request a new feature for Mercury Core
labels:
    - enhancement

body:
    - type: textarea
      id: problem
      attributes:
          label: Describe the problem
          description: Please provide a clear and concise description the problem this feature would solve, with as much detail as possible.
          placeholder: Currently, I have to...
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Describe the proposed solution
          description: Please provide a clear and concise description of what you would like to happen.
          placeholder: I propose the ability to...
      validations:
          required: true
